### ISSUE TITLE
Works on simulator but on iOS 7 device after the alertview is dismissed the view is unresponsive

### ISSUE THREAD

**Issue by paulhavey** [jsauve/SIAlertView.Xamarin#2]

**Comment by jgold6** [comment]
Adding:
this._AlertWindow.Dispose();
to the end of the 
public void DismissAnimated(bool animated, bool cleanup) 
method seems to resolve this issue. Apparently the key window created for the SIAlertView is still active and blocking the original window.

Gist of modified SIAlertView.cs file is here: https://gist.github.com/jgold6/f4ae5cb770e53f34b8ec

**Comment by jsauve** [comment]
Yeah, I had the same issue way back when I last worked on this. Nice fix, @jgold6 !! I'll add it. Manually managing windows should usually be avoided in iOS, but since UIAlertView appears in one, its kind of unavoidable. The alternative would be to simply add a view to the current view hierarchy, but since the keyboard also sits in its own UIWindow (not to mention the cursor itself being in its own UIWindow!), it's possible that the keyboard could sit over the top of an alert view that was displayed in that way. So, its right to use UIWindow here, but its definitely a pain in the arse. Again, nice fix, @jgold6 !!

**Comment by jgold6** [comment]
Thanks! I saw that the same issue had appeared in the original Obj-C version as well.

**Comment by jsauve** [comment]
Just committed change from @jgold6.
